# Generated by Django 2.2.5 on 2020-06-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='商家名称')),
                ('url', models.CharField(max_length=256, verbose_name='网址')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '商家信息',
                'verbose_name_plural': '商家信息',
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=256, verbose_name='机房')),
                ('dc', models.CharField(max_length=256, verbose_name='CPU')),
                ('cpu', models.CharField(max_length=256, verbose_name='CPU')),
                ('disk', models.CharField(max_length=256, verbose_name='硬盘')),
                ('bandwidth', models.CharField(max_length=256, verbose_name='带宽')),
                ('traffic', models.CharField(max_length=256, verbose_name='流量')),
                ('route', models.CharField(max_length=256, verbose_name='线路')),
                ('ipv4', models.CharField(max_length=256, verbose_name='IPV4')),
                ('arch', models.CharField(choices=[(0, '离线'), (1, '在线')], max_length=256, verbose_name='架构')),
                ('annual', models.CharField(max_length=256, verbose_name='年付')),
                ('quarter', models.CharField(max_length=256, verbose_name='季付')),
                ('month', models.CharField(max_length=256, verbose_name='月付')),
                ('pid', models.IntegerField(verbose_name='PID')),
                ('stock', models.IntegerField(choices=[(0, '无货'), (1, '有货')], default=1, verbose_name='库存')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vps.Company', verbose_name='商家')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'goods',
                'managed': True,
            },
        ),
    ]
