# Generated by Django 2.2.5 on 2020-06-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0002_auto_20200615_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='annual',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='年付'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='month',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='月付'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quarter',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='季付'),
        ),
    ]
