# Generated by Django 2.2.5 on 2020-06-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0003_auto_20200615_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='annual',
            field=models.IntegerField(max_length=11, verbose_name='年付'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='cpu',
            field=models.IntegerField(default=1, max_length=2, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='dc',
            field=models.CharField(choices=[('LA', 'LA'), ('HK', 'HK')], max_length=256, verbose_name='机房位置'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='ipv4',
            field=models.IntegerField(default=1, max_length=2, verbose_name='IPV4'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='month',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='月付'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quarter',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='季付'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='route',
            field=models.CharField(choices=[('CN2-GT', 'CN2-GT'), ('CN2-GIA', 'CN2-GIA'), ('PCCW', 'PCCW')], max_length=256, verbose_name='线路'),
        ),
    ]
