# Generated by Django 2.2.5 on 2020-06-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0007_auto_20200615_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='outOfStockString',
            field=models.CharField(default='Out of Stock', max_length=256, verbose_name='缺货字符串'),
        ),
    ]
