# Generated by Django 2.2.5 on 2020-06-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0008_company_outofstockstring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='outOfStockString',
            new_name='out_of_stock_string',
        ),
    ]
