# Generated by Django 2.2.5 on 2020-06-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0009_auto_20200616_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='cpu',
            field=models.IntegerField(default=1, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='ipv4',
            field=models.IntegerField(default=1, verbose_name='IPV4'),
        ),
    ]
