# Generated by Django 2.2.7 on 2020-06-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0012_company_need_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='need_monitor',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否需要监控'),
        ),
    ]
