# Generated by Django 2.2.7 on 2020-06-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0013_auto_20200623_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='dc',
            field=models.CharField(choices=[('ATL', 'ATL'), ('LA', 'LA'), ('SEA', 'SEA'), ('HK', 'HK'), ('Taiwan', 'Taiwan'), ('Frankfurt', 'Frankfurt')], max_length=256, verbose_name='机房位置'),
        ),
    ]
