# Generated by Django 2.2.5 on 2020-06-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0020_auto_20200623_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='is_topic',
        ),
        migrations.AddField(
            model_name='goods',
            name='sort',
            field=models.IntegerField(default=99, help_text='数字越大越靠前', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='dc',
            field=models.CharField(choices=[('ATL', 'ATL'), ('LA', 'LA'), ('SEA', 'SEA'), ('HK', 'HK'), ('Taiwan', 'Taiwan'), ('Frankfurt', 'Frankfurt'), ('China', 'China')], max_length=256, verbose_name='机房位置'),
        ),
    ]
