# Generated by Django 2.2.7 on 2020-07-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0021_auto_20200623_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '订阅通知',
                'verbose_name_plural': '订阅通知',
                'db_table': 'subscribe',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='connect_pid',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='连接PID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='need_monitor',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='检查库存'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='dc',
            field=models.CharField(choices=[('ATL', 'ATL'), ('LA', 'LA'), ('SEA', 'SEA'), ('HK', 'HK'), ('Taiwan', 'Taiwan'), ('Frankfurt', 'Frankfurt'), ('China', 'China'), ('Overseas', 'Overseas'), ('Global', 'Global')], max_length=256, verbose_name='机房位置'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sort',
            field=models.IntegerField(default=66, help_text='数字越大越靠前', verbose_name='排序'),
        ),
    ]
