# Generated by Django 2.2.5 on 2020-07-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0022_auto_20200708_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='status',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='有效性'),
        ),
    ]
